from typing import Optional

from pydantic import BaseModel, EmailStr


class User(BaseModel):
    id: str  # Unique user id generated by the database
    email: Optional[EmailStr] = None
    anonymous_id: Optional[str] = None


class UserDB(User):
    hashed_password: Optional[str] = None
